import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ShieldAlert } from "lucide-react";

const STORAGE_KEY = "hu_medical_disclaimer_accepted";

export function MedicalDisclaimerModal() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const accepted = localStorage.getItem(STORAGE_KEY);
    if (!accepted) setOpen(true);
  }, []);

  const handleAccept = () => {
    localStorage.setItem(STORAGE_KEY, "true");
    setOpen(false);
  };

  return (
    <Dialog open={open} onOpenChange={() => {}}>
      <DialogContent
        className="max-w-lg bg-card border-border"
        onInteractOutside={(e) => e.preventDefault()}
        onEscapeKeyDown={(e) => e.preventDefault()}
      >
        <DialogHeader>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 rounded-lg bg-amber-500/10 border border-amber-500/20">
              <ShieldAlert className="w-5 h-5 text-amber-400" />
            </div>
            <DialogTitle className="text-lg font-semibold">Medical Disclaimer</DialogTitle>
          </div>
        </DialogHeader>

        <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
          <p>
            <strong className="text-foreground">Human Upgrade OS is not a medical device</strong> and does not provide medical advice, diagnosis, or treatment.
          </p>
          <p>
            All content, including biomarker analysis, biological age calculations, supplement recommendations, peptide protocols, and meal plans, is provided <strong className="text-foreground">for informational and educational purposes only</strong>.
          </p>
          <p>
            The information generated by our AI should not be used as a substitute for professional medical advice. <strong className="text-foreground">Always consult a qualified healthcare provider</strong> before making any changes to your diet, supplements, medications, or health routine.
          </p>
          <p>
            By using Human Upgrade OS, you acknowledge that you are responsible for your own health decisions and that you have read and agreed to our{" "}
            <a href="/terms" target="_blank" className="text-brand-red hover:underline">Terms of Service</a>
            {" "}and{" "}
            <a href="/privacy" target="_blank" className="text-brand-red hover:underline">Privacy Policy</a>.
          </p>
        </div>

        <Button
          onClick={handleAccept}
          className="w-full bg-brand-red hover:bg-brand-red/90 rounded-full mt-2"
        >
          I Understand & Accept
        </Button>
      </DialogContent>
    </Dialog>
  );
}
